### PR TITLE
detect DataStructures.OrderedDict in Pkg.build, not __init__

### PR DESCRIPTION
**Pull request by stevengj**
This avoids the precompilation problem with using `@eval import DataStructures` in `__init__` (noted in fe9de2d226619ea52510479bc30b9acaad77628d) by moving this test from `__init__` to `build` time.  cc @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
Don't think this fixes the error since you could build JSON with datastructures support, remove datastructures, then `using JSON` would fail. Maybe the base stale cache file detection should be modified to not fail fatally when a precompiled dependency is missing, just mark as stale in that case.

**Comment by stevengj** [comment]
Alternatively, we could just `REQUIRE` DataStructures and be done with it.

**Comment by tkelman** [comment]
That would introduce another point of failure for JSON, when many people can get away without the ordered functionality. Perhapa other way around, have DataStructures require JSON so anyone who needs ordered JSON can get it via DataStructures

**Comment by tkelman** [comment]
Or a tiny separate OrderedJSON.jl package that depends on both

**Comment by stevengj** [comment]
Or we could just modify `parse_object` to let you pass in your own `dict` type:
```jl
function parse_object{T<:AbstractString,D<:Associative}(ps::ParserState{T}, dict::Type{D}=Dict)
    parse_object(ps, ordered, dict{KEY_TYPES,TYPES}())
end
```
then you could pass in `OrderedDict` or whatever you want to get any desired order.

**Comment by tkelman** [comment]
I like that idea better.

**Comment by stevengj** [comment]
Of course, that is a breaking change.  But of the 34 packages that currently `REQUIRE` JSON, apparently none of them use the `ordered` keyword option.

**Comment by stevengj** [comment]
Okay, closing this in favor of #129.

**Pull request closed without merging**
