### PR TITLE
Fix a bunch of deprecation warnings on v0.4

### PR DESCRIPTION
**Pull request by mweastwood**
This supersedes #101 and should get the Travis builds passing again.

### CODE REVIEW

**Comment by quinnj** [comment]
Does this fix the clobbering of Base `parse` method too?

**Comment by mweastwood** [comment]
The `JSON.parse` method is not renamed, but I explicitly qualify `Base.parse` when it's needed.

**Comment by quinnj** [comment]
Cool, looks good.

**Comment by stevengj** [comment]
Whoops, sorry, I just clobbered this patch with 20badf3d11592a31d13deca5a6595cae13e06918 which fixed the `Base.parse` issue ... can you rebase and then we can merge this?

**Comment by stevengj** [comment]
Rebased in #105

**Pull request closed without merging**
