### PR TITLE
fix mmap deprecation warning

### LINKED ISSUE #115: Deprecation warning on mmap_array
See below:

```
WARNING: mmap_array{T,N}(::Type{T},dims::NTuple{N,Integer},s::IO,offset=position(s)) is deprecated, use Mmap.mmap(s,Array{T,N},dims,offset) instead.
 in depwarn at ./deprecated.jl:63
 in mmap_array at deprecated.jl:49
 in mmap_array at deprecated.jl:48
 in anonymous at /Users/dhlin/.julia/v0.4/JSON/src/JSON.jl:280
 in open at iostream.jl:114
 in parsefile at /Users/dhlin/.julia/v0.4/JSON/src/JSON.jl:279
 in verify_and_test_drive at /Users/dhlin/.julia/v0.4/Distributions/test/univariates.jl:10
 in anonymous at no file:121
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in anonymous at no file:32
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
```

### PR DESCRIPTION
**Pull request by mweastwood**
fixes #115 

`Compat.jl` should take care of the v0.3 compatibility.

### CODE REVIEW

**Comment by tkelman** [comment]
This should declare the dependency on the version of Compat where this was added in `REQUIRE`

**Comment by mweastwood** [comment]
I think that's right. The minimum version of Compat is now specified in `REQUIRE`.

**Comment by mweastwood** [comment]
Can this be merged?

**Comment by mweastwood** [comment]
Thanks.

**Pull request merged**
