### PR TITLE
Fix #152, fix deprecation warning

### LINKED ISSUE #152: BoundsError: attempt to access 2x0 Array{Float64,2} at index [1:2,1]
I apologize if this is a duplicated issue or unrelated to JSON.jl.

Julia version: 0.4.6
JSON version: 0.6.0

image

### PR DESCRIPTION
**Pull request by TotalVerb**
The first commit fixes #152 and adds tests.

The second commit is unrelated, but since it is a change in the same function, I have included it in this PR.

cc @xqrongm

### CODE REVIEW

**Comment by TotalVerb** [comment]
Bump.

**Comment by kmsquire** [comment]
Thanks, and thanks for the bump!

**Comment by kmsquire** [comment]
@TotalVerb, do you have commit access here?  I can't tell, but if you don't, I'll request it for you.

**Comment by TotalVerb** [comment]
@kmsquire Thanks for the invitation. I do now.

**Pull request merged**
